FROM apache/superset:latest

USER root

RUN apt-get update && apt-get install -y python3-pip && \
    pip install --no-cache-dir --target /app/.venv/lib/python3.10/site-packages duckdb duckdb-engine && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

USER superset
